import { db } from './db';

const T = () => new Date().toISOString().slice(0, 10);

export async function seedIfEmpty(): Promise<void> {
  const count = await db.projects.count();
  if (count > 0) return;

  // Add projects and capture their auto-generated numeric IDs
  const [p1, p2, p3, p4, p5] = await Promise.all([
    db.projects.add({
      code: 'PRJ-001',
      name: 'Torre Residencial Mirador',
      client: 'Inmobiliaria Pacífico',
      location: 'San José, Costa Rica',
      status: 'active',
      startDate: '2025-03-01',
      endDate: '2026-09-30',
      budget: 4_800_000,
      manager: 'Ana Solís',
      progress: 40,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.projects.add({
      code: 'PRJ-002',
      name: 'Centro Comercial Plaza Norte',
      client: 'Grupo Inversiones CR',
      location: 'Heredia, Costa Rica',
      status: 'active',
      startDate: '2025-01-15',
      endDate: '2026-06-30',
      budget: 8_200_000,
      manager: 'Ricardo Mora',
      progress: 65,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.projects.add({
      code: 'PRJ-003',
      name: 'Puente Río Reventazón',
      client: 'MOPT',
      location: 'Cartago, Costa Rica',
      status: 'planning',
      startDate: '2025-07-01',
      endDate: '2026-12-31',
      budget: 12_500_000,
      manager: 'Marco Jiménez',
      progress: 0,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.projects.add({
      code: 'PRJ-004',
      name: 'Bodega Industrial Zona Franca',
      client: 'LogiCR S.A.',
      location: 'Alajuela, Costa Rica',
      status: 'completed',
      startDate: '2024-06-01',
      endDate: '2025-02-28',
      budget: 2_100_000,
      manager: 'Ana Solís',
      progress: 100,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.projects.add({
      code: 'PRJ-005',
      name: 'Remodelación Hospital Calderón',
      client: 'CCSS',
      location: 'San José, Costa Rica',
      status: 'on-hold',
      startDate: '2025-02-01',
      endDate: '2025-12-31',
      budget: 3_400_000,
      manager: 'Valeria Castro',
      progress: 20,
      createdAt: T(),
      updatedAt: T(),
    }),
  ]);

  await Promise.all([
    db.equipment.add({
      code: 'EQ-001',
      name: 'Excavadora Hidráulica',
      category: 'Movimiento de Tierra',
      model: 'CAT 320GX',
      serialNumber: 'CAT320-2023-0441',
      status: 'in-use',
      assignedProjectId: p1,
      lastMaintenance: '2025-03-15',
      nextMaintenance: '2025-06-15',
      dailyRate: 1_200,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.equipment.add({
      code: 'EQ-002',
      name: 'Grúa Torre',
      category: 'Elevación',
      model: 'Liebherr 200 EC-H',
      serialNumber: 'LBH-EC200-2022-0089',
      status: 'in-use',
      assignedProjectId: p2,
      lastMaintenance: '2025-01-10',
      nextMaintenance: '2025-04-10',
      dailyRate: 2_800,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.equipment.add({
      code: 'EQ-003',
      name: 'Concretera Mezcladora',
      category: 'Concreto',
      model: 'FIORI DB 460',
      serialNumber: 'FIO-DB460-2021-0334',
      status: 'available',
      assignedProjectId: null,
      lastMaintenance: '2025-04-01',
      nextMaintenance: '2025-07-01',
      dailyRate: 350,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.equipment.add({
      code: 'EQ-004',
      name: 'Compactadora de Suelo',
      category: 'Compactación',
      model: 'Bomag BW 211 D',
      serialNumber: 'BOM-BW211-2020-0178',
      status: 'maintenance',
      assignedProjectId: null,
      lastMaintenance: '2025-04-20',
      nextMaintenance: '2025-05-20',
      dailyRate: 480,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.equipment.add({
      code: 'EQ-005',
      name: 'Camión Volqueta 15m³',
      category: 'Transporte',
      model: 'Mercedes Actros 3351',
      serialNumber: 'MB-ACT3351-2022-0612',
      status: 'in-use',
      assignedProjectId: p1,
      lastMaintenance: '2025-02-28',
      nextMaintenance: '2025-05-28',
      dailyRate: 900,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.equipment.add({
      code: 'EQ-006',
      name: 'Generador Eléctrico 200kVA',
      category: 'Energía',
      model: 'Cummins C200D5',
      serialNumber: 'CUM-C200D5-2023-0291',
      status: 'available',
      assignedProjectId: null,
      lastMaintenance: '2025-03-20',
      nextMaintenance: '2025-06-20',
      dailyRate: 420,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.equipment.add({
      code: 'EQ-007',
      name: 'Andamio Multidireccional',
      category: 'Acceso en Altura',
      model: 'Layher Allround 70',
      serialNumber: 'LAY-AR70-2019-0089',
      status: 'in-use',
      assignedProjectId: p2,
      lastMaintenance: '2025-01-05',
      nextMaintenance: '2025-07-05',
      dailyRate: 200,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.equipment.add({
      code: 'EQ-008',
      name: 'Miniexcavadora',
      category: 'Movimiento de Tierra',
      model: 'Kubota KX057-5',
      serialNumber: 'KUB-KX057-2022-0503',
      status: 'available',
      assignedProjectId: null,
      lastMaintenance: '2025-04-10',
      nextMaintenance: '2025-07-10',
      dailyRate: 650,
      createdAt: T(),
      updatedAt: T(),
    }),
  ]);

  await Promise.all([
    db.materials.add({
      code: 'MAT-001',
      name: 'Cemento Portland Tipo I',
      category: 'Aglomerantes',
      unit: 'bag',
      stockQuantity: 1200,
      minStock: 500,
      unitCost: 12.5,
      supplier: 'Cementos Argos CR',
      lastRestocked: '2025-04-15',
      assignedProjectId: p1,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.materials.add({
      code: 'MAT-002',
      name: 'Varilla Corrugada #4',
      category: 'Acero',
      unit: 'unit',
      stockQuantity: 340,
      minStock: 200,
      unitCost: 18.75,
      supplier: 'Aceros Costa Rica',
      lastRestocked: '2025-04-10',
      assignedProjectId: p1,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.materials.add({
      code: 'MAT-003',
      name: 'Arena de Río',
      category: 'Agregados',
      unit: 'm3',
      stockQuantity: 85,
      minStock: 30,
      unitCost: 28.0,
      supplier: 'Agregados del Valle',
      lastRestocked: '2025-04-18',
      assignedProjectId: null,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.materials.add({
      code: 'MAT-004',
      name: 'Piedra Cuartilla',
      category: 'Agregados',
      unit: 'm3',
      stockQuantity: 62,
      minStock: 40,
      unitCost: 32.0,
      supplier: 'Agregados del Valle',
      lastRestocked: '2025-04-18',
      assignedProjectId: null,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.materials.add({
      code: 'MAT-005',
      name: 'Block de Concreto 15x20x40',
      category: 'Mampostería',
      unit: 'unit',
      stockQuantity: 8400,
      minStock: 2000,
      unitCost: 0.85,
      supplier: 'Prefabricados Nacional',
      lastRestocked: '2025-04-05',
      assignedProjectId: p2,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.materials.add({
      code: 'MAT-006',
      name: 'Lámina de Zinc Calibre 26',
      category: 'Cubiertas',
      unit: 'm2',
      stockQuantity: 120,
      minStock: 200,
      unitCost: 8.5,
      supplier: 'Metalco CR',
      lastRestocked: '2025-03-28',
      assignedProjectId: null,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.materials.add({
      code: 'MAT-007',
      name: 'Tubería PVC 4" SDR-41',
      category: 'Plomería',
      unit: 'unit',
      stockQuantity: 95,
      minStock: 50,
      unitCost: 14.2,
      supplier: 'Amanco CR',
      lastRestocked: '2025-04-12',
      assignedProjectId: p1,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.materials.add({
      code: 'MAT-008',
      name: 'Pintura Látex Exterior',
      category: 'Acabados',
      unit: 'liter',
      stockQuantity: 42,
      minStock: 100,
      unitCost: 6.8,
      supplier: 'Pinturas Sur',
      lastRestocked: '2025-03-10',
      assignedProjectId: null,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.materials.add({
      code: 'MAT-009',
      name: 'Cable THW #10 AWG',
      category: 'Eléctrico',
      unit: 'roll',
      stockQuantity: 28,
      minStock: 15,
      unitCost: 145.0,
      supplier: 'Condumex CR',
      lastRestocked: '2025-04-08',
      assignedProjectId: p2,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.materials.add({
      code: 'MAT-010',
      name: 'Concreto Premezclado 210 kg/cm²',
      category: 'Concreto',
      unit: 'm3',
      stockQuantity: 0,
      minStock: 10,
      unitCost: 95.0,
      supplier: 'CEMEX CR',
      lastRestocked: '2025-04-20',
      assignedProjectId: p1,
      createdAt: T(),
      updatedAt: T(),
    }),
  ]);

  await Promise.all([
    // PRJ-001 budget items
    db.budgetItems.add({
      projectId: p1,
      category: 'labor',
      description: 'Mano de obra civil',
      budgeted: 960_000,
      actual: 384_000,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.budgetItems.add({
      projectId: p1,
      category: 'materials',
      description: 'Materiales de construcción',
      budgeted: 1_920_000,
      actual: 768_000,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.budgetItems.add({
      projectId: p1,
      category: 'equipment',
      description: 'Alquiler de equipo pesado',
      budgeted: 720_000,
      actual: 480_000,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.budgetItems.add({
      projectId: p1,
      category: 'subcontract',
      description: 'Subcontratos MEP',
      budgeted: 960_000,
      actual: 240_000,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.budgetItems.add({
      projectId: p1,
      category: 'overhead',
      description: 'Gastos generales',
      budgeted: 240_000,
      actual: 48_000,
      createdAt: T(),
      updatedAt: T(),
    }),
    // PRJ-002
    db.budgetItems.add({
      projectId: p2,
      category: 'labor',
      description: 'Mano de obra especializada',
      budgeted: 1_640_000,
      actual: 1_066_000,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.budgetItems.add({
      projectId: p2,
      category: 'materials',
      description: 'Estructura metálica y acabados',
      budgeted: 3_280_000,
      actual: 2_132_000,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.budgetItems.add({
      projectId: p2,
      category: 'equipment',
      description: 'Grúa y equipo elevación',
      budgeted: 1_640_000,
      actual: 1_066_000,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.budgetItems.add({
      projectId: p2,
      category: 'subcontract',
      description: 'Instalaciones especiales',
      budgeted: 1_230_000,
      actual: 820_000,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.budgetItems.add({
      projectId: p2,
      category: 'overhead',
      description: 'Administración y overhead',
      budgeted: 410_000,
      actual: 246_000,
      createdAt: T(),
      updatedAt: T(),
    }),
    // PRJ-003
    db.budgetItems.add({
      projectId: p3,
      category: 'labor',
      description: 'Mano de obra estructural',
      budgeted: 3_750_000,
      actual: 0,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.budgetItems.add({
      projectId: p3,
      category: 'materials',
      description: 'Acero y concreto',
      budgeted: 5_000_000,
      actual: 0,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.budgetItems.add({
      projectId: p3,
      category: 'equipment',
      description: 'Equipo especializado',
      budgeted: 2_500_000,
      actual: 0,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.budgetItems.add({
      projectId: p3,
      category: 'subcontract',
      description: 'Estudios y diseño',
      budgeted: 750_000,
      actual: 0,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.budgetItems.add({
      projectId: p3,
      category: 'overhead',
      description: 'Costos indirectos',
      budgeted: 500_000,
      actual: 0,
      createdAt: T(),
      updatedAt: T(),
    }),
    // PRJ-005
    db.budgetItems.add({
      projectId: p5,
      category: 'labor',
      description: 'Personal técnico',
      budgeted: 680_000,
      actual: 136_000,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.budgetItems.add({
      projectId: p5,
      category: 'materials',
      description: 'Materiales especializados',
      budgeted: 1_360_000,
      actual: 272_000,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.budgetItems.add({
      projectId: p5,
      category: 'equipment',
      description: 'Equipo médico y técnico',
      budgeted: 850_000,
      actual: 170_000,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.budgetItems.add({
      projectId: p5,
      category: 'subcontract',
      description: 'Subcontratos especializados',
      budgeted: 340_000,
      actual: 68_000,
      createdAt: T(),
      updatedAt: T(),
    }),
    db.budgetItems.add({
      projectId: p5,
      category: 'overhead',
      description: 'Gastos administrativos',
      budgeted: 170_000,
      actual: 34_000,
      createdAt: T(),
      updatedAt: T(),
    }),
  ]);

  // Suppress unused variable warning — p4 has no budget items in the original data
  void p4;
}
